[
  { "title": "Help clean backyard #1", "description": "Auto-generated anonymous favour", "reward": ["cookies"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Pick up groceries #2", "description": "Auto-generated anonymous favour", "reward": ["gift card"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Walk the dog #3", "description": "Auto-generated anonymous favour", "reward": ["thank you note"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Donate old clothes #4", "description": "Auto-generated anonymous favour", "reward": ["points"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Water the plants #5", "description": "Auto-generated anonymous favour", "reward": ["smile"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Take out trash #6", "description": "Auto-generated anonymous favour", "reward": ["cookies"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Feed the neighbor's cat #7", "description": "Auto-generated anonymous favour", "reward": ["gift card"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Mow the lawn #8", "description": "Auto-generated anonymous favour", "reward": ["thank you note"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Wash car #9", "description": "Auto-generated anonymous favour", "reward": ["points"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Organize bookshelf #10", "description": "Auto-generated anonymous favour", "reward": ["smile"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Help clean backyard #11", "description": "Auto-generated anonymous favour", "reward": ["cookies"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Pick up groceries #12", "description": "Auto-generated anonymous favour", "reward": ["gift card"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Walk the dog #13", "description": "Auto-generated anonymous favour", "reward": ["thank you note"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Donate old clothes #14", "description": "Auto-generated anonymous favour", "reward": ["points"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Water the plants #15", "description": "Auto-generated anonymous favour", "reward": ["smile"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Take out trash #16", "description": "Auto-generated anonymous favour", "reward": ["cookies"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Feed the neighbor's cat #17", "description": "Auto-generated anonymous favour", "reward": ["gift card"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Mow the lawn #18", "description": "Auto-generated anonymous favour", "reward": ["thank you note"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Wash car #19", "description": "Auto-generated anonymous favour", "reward": ["points"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Organize bookshelf #20", "description": "Auto-generated anonymous favour", "reward": ["smile"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Help clean backyard #21", "description": "Auto-generated anonymous favour", "reward": ["cookies"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Pick up groceries #22", "description": "Auto-generated anonymous favour", "reward": ["gift card"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Walk the dog #23", "description": "Auto-generated anonymous favour", "reward": ["thank you note"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Donate old clothes #24", "description": "Auto-generated anonymous favour", "reward": ["points"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Water the plants #25", "description": "Auto-generated anonymous favour", "reward": ["smile"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Take out trash #26", "description": "Auto-generated anonymous favour", "reward": ["cookies"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Feed the neighbor's cat #27", "description": "Auto-generated anonymous favour", "reward": ["gift card"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Mow the lawn #28", "description": "Auto-generated anonymous favour", "reward": ["thank you note"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Wash car #29", "description": "Auto-generated anonymous favour", "reward": ["points"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Organize bookshelf #30", "description": "Auto-generated anonymous favour", "reward": ["smile"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Help clean backyard #31", "description": "Auto-generated anonymous favour", "reward": ["cookies"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Pick up groceries #32", "description": "Auto-generated anonymous favour", "reward": ["gift card"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Walk the dog #33", "description": "Auto-generated anonymous favour", "reward": ["thank you note"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Donate old clothes #34", "description": "Auto-generated anonymous favour", "reward": ["points"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Water the plants #35", "description": "Auto-generated anonymous favour", "reward": ["smile"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Take out trash #36", "description": "Auto-generated anonymous favour", "reward": ["cookies"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Feed the neighbor's cat #37", "description": "Auto-generated anonymous favour", "reward": ["gift card"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Mow the lawn #38", "description": "Auto-generated anonymous favour", "reward": ["thank you note"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Wash car #39", "description": "Auto-generated anonymous favour", "reward": ["points"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Organize bookshelf #40", "description": "Auto-generated anonymous favour", "reward": ["smile"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Help clean backyard #41", "description": "Auto-generated anonymous favour", "reward": ["cookies"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Pick up groceries #42", "description": "Auto-generated anonymous favour", "reward": ["gift card"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Walk the dog #43", "description": "Auto-generated anonymous favour", "reward": ["thank you note"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Donate old clothes #44", "description": "Auto-generated anonymous favour", "reward": ["points"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Water the plants #45", "description": "Auto-generated anonymous favour", "reward": ["smile"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Take out trash #46", "description": "Auto-generated anonymous favour", "reward": ["cookies"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Feed the neighbor's cat #47", "description": "Auto-generated anonymous favour", "reward": ["gift card"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Mow the lawn #48", "description": "Auto-generated anonymous favour", "reward": ["thank you note"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Wash car #49", "description": "Auto-generated anonymous favour", "reward": ["points"], "status": "pending", "favourType": "public", "isAnonymous": true },
  { "title": "Organize bookshelf #50", "description": "Auto-generated anonymous favour", "reward": ["smile"], "status": "pending", "favourType": "public", "isAnonymous": true }
]
